No adding ffpe with wg tag
Clinical-Genomics/cgweb pull request #238
Opened 2020-11-05 09:11 UTC by elevu

This PR forces customer to not use FFPE sample sources when a WG* application is selected.

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.sclifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] try to upload a sample and select a WG* application and a FFPE sample

**Expected test outcome**:
- [x] check that you are not allowed to save such a sample
- [x] Take a screenshot and attach or copy/paste the output.

![Screen Shot 2020-11-05 at 10 06 48](https://user-images.githubusercontent.com/6919697/98220865-3b23a000-1f4f-11eb-9f45-fbd2c6b4a2ea.png)

**Review:**
- [ ] code approved by
- [x] tests executed by EM
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2020-11-05 09:19 UTC, annaengstrom commented on store/getters.js
> +  if (sample.application.includes("WG") && sample.source.includes("FFPE"))
Does this mean that the app tag must start with "WG" or can "WG" be placed anywhere in the app tag?

2020-11-05 09:23 UTC, elevu commented on store/getters.js
> +  if (sample.application.includes("WG") && sample.source.includes("FFPE"))
> Does this mean that the app tag must start with "WG" or can "WG" be placed anywhere in the app tag?

Anywhere in the tag. Should it be only at the beginning?

2020-11-05 09:27 UTC, annaengstrom commented on store/getters.js
> +  if (sample.application.includes("WG") && sample.source.includes("FFPE"))
Yes, should only be two first characters of app tag. We have "M**WG**NXTR003" as an example which should not be affected by this.

2020-11-05 09:34 UTC, elevu commented on store/getters.js
> +  if (sample.application.includes("WG") && sample.source.includes("FFPE"))
Changed, FFPE is not showing anyway up as an option for microbial WG, but I edited to startsWith just in case.

2020-11-09 07:26 UTC, patrikgrenfeldt requested changes
Seems like you solved the problem :) I think we could shortly discuss the way we validate in this application to see if we can simplify/improve it

2020-11-09 07:26 UTC, patrikgrenfeldt commented on store/getters.js
> +            hasFFPEandWGtag(sample),
```suggestion
            isNotFFPEandWGtag(sample),
```
seems like the name is reversed to the logic in the function, right?

2020-11-09 07:26 UTC, patrikgrenfeldt commented on store/getters.js
> +export const hasFFPEandWGtag = (sample) => {
```suggestion
export const isNotFFPEandWGtag = (sample) => {
```
I wonder if it would make sense to name it something along the lines of what WG actually stands for, to make it more into an abstraction. what do you think?

2020-11-09 08:07 UTC, elevu commented on store/getters.js
> +export const hasFFPEandWGtag = (sample) => {
Something like isNotFFPEinWholeGenomeTag ?

2020-11-09 13:34 UTC, patrikgrenfeldt approved these changes
👍

2020-11-10 07:57 UTC, merged