Limit samples and tumours in balsamic
Clinical-Genomics/cgweb pull request #239
Opened 2020-11-05 15:32 UTC by elevu

This PR addresses https://github.com/Clinical-Genomics/cgweb/issues/232 , it hinders customer from submitting Balsamic analysis with more then two samples per family, more the one tumour or no tumours. Will deployed to staging for today but if you need help testing it let me know, I can deploy to staging for you.

**How to prepare for test**:
- [x] ssh to clinical-db
- [x] install on stage of clinical-db:
`bash servers/resources/clinical-db.sclifelab.se/update-cgweb-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] login on https://clinical-stage.scilifelab.se/
- [x] try to submit a Balsamic order with more than 2 samples, more then 1 tumour or no tumours.

**Expected test outcome**:
- [x] check that validation works as expected
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by EM
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

The number of samples is validated when trying to Submit the order:
![Screen Shot 2020-11-05 at 16 19 03](https://user-images.githubusercontent.com/6919697/98260574-c74fba80-1f83-11eb-979b-7faf250873aa.png)

While the tumour amount is validated in the forms
![Screen Shot 2020-11-05 at 16 18 47](https://user-images.githubusercontent.com/6919697/98260585-c9b21480-1f83-11eb-8958-c5e255687bb1.png)

A warning is added when selecting Balsamic analysis
![Screen Shot 2020-11-05 at 16 18 35](https://user-images.githubusercontent.com/6919697/98260871-1990db80-1f84-11eb-9921-e98d3bec7d36.png)

A help message was also added
![Screen Shot 2020-11-05 at 16 29 12](https://user-images.githubusercontent.com/6919697/98260949-35947d00-1f84-11eb-96d9-2e9c6bbbc830.png)

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2020-11-05 18:18 UTC, emmser commented
Change 'Family' to 'Case' instead. Family should be avoided. otherwise it looks good!

2020-11-06 06:42 UTC, annagellerbring approved these changes
looks good from what I can see!

2020-11-06 07:29 UTC, elevu commented
> Change 'Family' to 'Case' instead. Family should be avoided. otherwise it looks good!

done!

2020-11-09 08:06 UTC, patrikgrenfeldt requested changes
Nice work, I have some comments :)

2020-11-09 08:06 UTC, patrikgrenfeldt commented on store/getters.js
> +function hasMoreTumours(list) {
```suggestion
function hasMultipleTumours(list) {
```

2020-11-09 08:06 UTC, patrikgrenfeldt commented on store/getters.js
> +  return tumourAmount > 1 ? true : false;
```suggestion
  let tumourCount = 0;
  list.forEach((sample) => {
    if (sample.tumour) tumourCount++;
  });
  return tumourCount > 1 ? true : false;
```
Amount sound like a volume or weight, right?

2020-11-09 08:06 UTC, patrikgrenfeldt commented on pages/order.vue
> +            this.hasBalsamicSampleError = true;
why don't we toast like with the other validations?

2020-11-09 08:11 UTC, elevu commented on components/order/OrderForm.vue
> +          >
Since this is a big and new change, I think it is good to somehow highlight it as soon as they select this type of order. It can be removed when the the customer get used to it. Ideally we should show all the new changes in a better way but since for now we don't have a fast way to do that, I think this is a good compromise

2020-11-09 08:18 UTC, elevu commented on pages/order.vue
> +            this.hasBalsamicSampleError = true;
Toast notification are temporary and should be used when informing the user of something that is not critical. I think that this kind of error has to be much more clearly displayed.

2020-11-09 10:49 UTC, elevu commented on pages/order.vue
> +          if you have questions
For now there is nothing written the provkrav page about this change, @annagellerbring or somebody else will add some instructions in another PR. Before the text is updated I think the link to the email is good enough, then it can be changed!

2020-11-09 12:36 UTC, patrikgrenfeldt commented on components/order/OrderForm.vue
> +          >
I'm sure we inform them in other channels as well. Could we have something like a banner? I see more areas of use there

2020-11-09 12:50 UTC, elevu commented on components/order/OrderForm.vue
> +          >
If we inform them in other ways, should I just remove it? And then we can think about a general better way to display new changes in the UI. What do you think about this @annagellerbring, will users be notified?

2020-11-09 13:32 UTC, patrikgrenfeldt approved these changes
👍

2020-11-09 14:16 UTC, annagellerbring commented on pages/order.vue
> +          if you have questions
No, that's correct! It's not updated yet on the website and I don't know where to put such information. I don't think it belongs in "provkrav" but rather in a new section in "beställningar" or "Applications".

2020-11-09 14:21 UTC, annagellerbring commented on components/order/OrderForm.vue
> +          >
To me it sounds good to highlight the change somewhere in the orderportal since this change helps us to stop orders that are placed by "old" customers without interacting with us much before placing it. What other channels are you referring to?

2020-11-10 09:02 UTC, merged